# Generated by Django 3.0.5 on 2020-04-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20200417_0244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(choices=[('1', 'Video Games'), ('2', 'Board Games'), ('3', 'Toys')], default='New Item', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('A', 'Asset'), ('L', 'Liability'), ('E', 'Equity')], default='A', max_length=1),
        ),
    ]
