# Generated by Django 3.0.5 on 2020-04-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20200417_0540'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='newItemName',
            field=models.CharField(default='New Item', max_length=50),
        ),
    ]
