# Generated by Django 3.0.5 on 2020-04-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_account_account_bal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_bal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25),
        ),
    ]
